workflow:
  rules:  # Do not create pipelines for tag updates
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

stages:
  - test

before_script:
  # Assumes CI executes on AEA compute servers
  - aea_compute_path="/projects/aea_compute"
  - aea_modulefiles="${aea_compute_path}/modulefiles"
  - module use ${aea_modulefiles}
  - environment_choices="aea-beta aea-release"
  - for env in ${environment_choices}; do if [[ -d "${aea_compute_path}/${env}" ]]; then environment=${env}; break; fi; done
  - echo ${environment}
  - module load ${environment}
  - conda info

test:
  stage: test
  variables:
    GIT_STRATEGY: clone
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - project_root=$PWD
    - cd ${project_root}/turbo_turtle/tests && abq2023 cae -noGui tests_geometry.py && cd ${project_root}
    - name='Turbo-Turtle-Tests'
    - python -m turbo_turtle.main --model-name ${name} --part-name sphere --output-file ${name} --center 0 0 0 --xpoint 1 0 0 --zpoint 0 0 1 --plane-angle 45
    - python -m turbo_turtle.main --model-name ${name} --part-name eigth-sphere --output-file ${name} --center 0 0 0 --xpoint 1 0 0 --zpoint 0 0 1 --plane-angle 45
    - python -m turbo_turtle.main --model-name ${name} --part-name quarter-sphere --output-file ${name} --center 0 0 0 --xpoint 1 0 0 --zpoint 0 0 1 --plane-angle 45
    - python -m turbo_turtle.main --model-name ${name} --part-name half-sphere --output-file ${name} --center 0 0 0 --xpoint 1 0 0 --zpoint 0 0 1 --plane-angle 45
    - python -m turbo_turtle.main --model-name ${name} --part-name seveneighths-sphere --output-file ${name} --center 0 0 0 --xpoint 1 0 0 --zpoint 0 0 1 --plane-angle 45
    - python -m turbo_turtle.main --model-name ${name} --part-name offset-sphere --output-file ${name} --center 1 1 0 --xpoint 2 1 0 --zpoint 1 1 1 --plane-angle 45
    - python -m turbo_turtle.main --model-name ${name} --part-name swiss-cheese --output-file ${name} --center 0 0 0 --xpoint 1 0 0 --zpoint 0 0 1 --plane-angle 45
  tags:
    - shell-aea
