workflow:
  rules:  # Do not create pipelines for tag updates
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

stages:
  - test
  - build
  - deploy

before_script:
  # Assumes CI executes on AEA compute servers
  - aea_compute_path="/projects/aea_compute"
  - aea_conda_channel="${aea_compute_path}/aea-conda"
  - aea_modulefiles="${aea_compute_path}/modulefiles"
  - module use ${aea_modulefiles}
  - environment_choices="aea-beta aea-release"
  - for env in ${environment_choices}; do if [[ -d "${aea_compute_path}/${env}" ]]; then environment=${env}; break; fi; done
  - echo ${environment}
  - module load ${environment}
  - conda info
  - conda_artifacts_directory='conda-bld'
  - project_root=$PWD

test:
  stage: test
  variables:
    GIT_STRATEGY: clone
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - scons html
    - cd ${project_root}/turbo_turtle/tests && abq2023 cae -noGui tests_geometry.py && cd ${project_root}
    - name='Turbo-Turtle-Tests'
    - python -m turbo_turtle.main --input-file ${project_root}/${name}.cae --output-file ${project_root}/${name}.cae --model-name ${name} --part-name sphere --center 0 0 0 --xpoint 1 0 0 --zpoint 0 0 1 --plane-angle 45
    - python -m turbo_turtle.main --input-file ${project_root}/${name}.cae --output-file ${project_root}/${name}.cae --model-name ${name} --part-name eigth-sphere --center 0 0 0 --xpoint 1 0 0 --zpoint 0 0 1 --plane-angle 45
    - python -m turbo_turtle.main --input-file ${project_root}/${name}.cae --output-file ${project_root}/${name}.cae --model-name ${name} --part-name quarter-sphere --center 0 0 0 --xpoint 1 0 0 --zpoint 0 0 1 --plane-angle 45
    - python -m turbo_turtle.main --input-file ${project_root}/${name}.cae --output-file ${project_root}/${name}.cae --model-name ${name} --part-name half-sphere --center 0 0 0 --xpoint 1 0 0 --zpoint 0 0 1 --plane-angle 45
    - python -m turbo_turtle.main --input-file ${project_root}/${name}.cae --output-file ${project_root}/${name}.cae --model-name ${name} --part-name seveneighths-sphere --center 0 0 0 --xpoint 1 0 0 --zpoint 0 0 1 --plane-angle 45
    - python -m turbo_turtle.main --input-file ${project_root}/${name}.cae --output-file ${project_root}/${name}.cae --model-name ${name} --part-name offset-sphere --center 1 1 0 --xpoint 2 1 0 --zpoint 1 1 1 --plane-angle 45
    - python -m turbo_turtle.main --input-file ${project_root}/${name}.cae --output-file ${project_root}/${name}.cae --model-name ${name} --part-name swiss-cheese --center 0 0 0 --xpoint 1 0 0 --zpoint 0 0 1 --plane-angle 45
  tags:
    - shell-aea

conda-build:
  stage: build
  variables:
    GIT_STRATEGY: clone
  dependencies: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "dev"
  script:
    # Set the LANL internal proxies
    - export ALL_PROXY="proxyout.lanl.gov:8080"
    - export HTTP_PROXY="http://$ALL_PROXY"
    - export HTTPS_PROXY=$HTTP_PROXY
    # Override default permissions. Set group to rx with no write permissions.
    - umask 0022
    - mkdir ${conda_artifacts_directory}
    - croot="/scratch/$USER/$(basename $PWD)/${conda_artifacts_directory}"
    # TODO: Remove the AEA conda channel when WAVESv0.7.2 or higher is released on conda-forge
    - VERSION=$(python -m setuptools_scm) conda build recipe-internal --channel /projects/aea_compute/aea-conda --channel conda-forge --no-anaconda-upload --croot ${croot} --output-folder ${conda_artifacts_directory}
    - conda build purge --croot ${croot}
  artifacts:
    expire_in: '2 hrs'
    paths:
      - conda-bld/noarch/turbo_turtle-*-*.tar.bz2
  tags:
    # sstelmo's version of git is too old for setuptools_scm
    - sstbigbird-shell-aea

deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: clone
  dependencies:
    - conda-build
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "dev"
  script:
    # Override default permissions. Set group to rx with no write permissions.
    - umask 0022
    # Copy Conda package to AEA Conda Channel
    - cp ${conda_artifacts_directory}/noarch/turbo_turtle-*-*.tar.bz2 ${aea_conda_channel}/noarch
    # Change group for access by all W-13 staff and prevent accidental modification by institutional account in CI jobs
    - chgrp w13users ${aea_conda_channel}/noarch/turbo_turtle-*-*.tar.bz2 || true
    - chmod 555 ${aea_conda_channel}/noarch/turbo_turtle-*-*.tar.bz2 || true
    # Update the AEA Conda Channel index
    - conda index ${aea_conda_channel}
    # Troubleshooting conda channel deploy and index update
    - conda search --channel file://${aea_conda_channel}/ --override-channels turbo_turtle
  tags:
    - shell-aea

# It MUST be called pages
pages:
  stage: deploy
  variables:
    GIT_STRATEGY: clone
  dependencies: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - rm -rf public && mkdir -p public
    # Ensure the ``_version.py`` file is created
    - python -m setuptools_scm
    - scons html --clean && scons html
    - cp -r build/docs/html/* public/
  artifacts:
    paths:
      # It MUST be called public
      - public
  tags:
    - shell-aea
