channels:
  - conda-forge

dependencies:
  - boa
  # TODO: Remove when conda-build 24.? no longer breaks boa/mambabuild
  - conda-build ==3.28
  - flake8
  - ipython
  - lazy_loader >=0.4
  - mypy
  - numpy
  - pandas
  - pip
  - pytest
  - pytest-cov
  - pytest-xdist
  - python-build
  - scons >=4
  - setuptools >=62
  - setuptools_scm[toml] >=6.2,<8
  - sphinx >=5.1
  - sphinx-argparse
  - sphinx-copybutton >=0.5.1
  - sphinx_rtd_theme >=1
  - sphinxcontrib-bibtex
  - waves >=0.7.2
