channels:
  - conda-forge

dependencies:
  - boa
  - flake8
  - ipython
  - lazy_loader >=0.4
  - mypy
  - numpy
  - pandas
  - pip
  - pytest
  - pytest-cov
  - pytest-xdist
  - python-build
  - scons >=4
  - setuptools >=64
  - setuptools_scm >=8
  - sphinx >=5.1
  - sphinx-argparse
  - sphinx-copybutton >=0.5.1
  - sphinx_rtd_theme >=1
  - sphinxcontrib-bibtex
  - twine
  - waves >=0.7.2
