package:
  name: turbo_turtle
  # TODO: Figure out how to use pyproject.toml and a Conda build Jinja template
  version: {{ VERSION }}

about:
  home: https://re-git.lanl.gov/aea/python-projects/turbo_turtle
  summary: 'Partition hollow, spherical bodies using a turtle shell'
  description: |
    Partition hollow, spherical bodies using a turtle shell
  doc_url: https://aea.re-pages.lanl.gov/python-projects/turbo_turtle/main/index.html
  dev_url: https://re-git.lanl.gov/aea/python-projects/turbo_turtle

source:
  path: '..'

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ VERSION }}
  script:
    # Build and install Conda package
    - $PYTHON -m build --no-isolation
    - $PYTHON -m pip install dist/$PKG_NAME-$PKG_VERSION.tar.gz --no-deps --ignore-installed -v --no-build-isolation
    - $PYTHON -m pip show $PKG_NAME
    # Build man page and HTML documentation to bundle in Conda package
    - scons man html
    - $PYTHON package_documentation.py
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - scons >=4
    - setuptools_scm[toml] >=6.2,<8
    - sphinx >=5.1
    - sphinx-argparse
    - sphinx-copybutton >=0.5.1
    - sphinx_rtd_theme >=1
    - waves >=0.7.2
  host:
    - python
    - python-build
    - pip
    - setuptools >=62
    - setuptools_scm[toml] >=6.2,<8
  run:
    - python >=3.8

test:
  requires:
    - numpy
    - pytest
    - pytest-xdist
  imports:
    - turbo_turtle
  source_files:
    - legacy_geometry.py
    - turbo_turtle/tests/washer.csv
    - turbo_turtle/tests/vase.csv
  commands:
    - test_root=${PWD}
    # Test as-installed project unit tests
    - cd $SP_DIR/$PKG_NAME
    - pytest -vvv --ignore=_abaqus_python
    - abq2023 python -m unittest discover _abaqus_python --verbose
    - cd ${test_root}
    # Help/usage tests
    - turbo-turtle -h
    - turbo-turtle docs -h
    - turbo-turtle docs --print-local-path
    - turbo-turtle geometry -h
    - turbo-turtle sphere -h
    - turbo-turtle partition -h
    - turbo-turtle mesh -h
    - turbo-turtle image -h
    - turbo-turtle merge -h
    - turbo-turtle export -h
    # System tests
    - turbo-turtle sphere --inner-radius 1 --outer-radius 2 --output-file sphere.cae --model-name sphere --part-name sphere --quadrant both --revolution-angle 360.0 --center 0.0 0.0
    - turbo-turtle partition --input-file sphere.cae --output-file sphere.cae --model-name sphere --part-name sphere --center 0.0 0.0 0 --xpoint 1.0 0.0 0.0 --zpoint 0.0 0.0 1.0 --plane-angle 45
    - turbo-turtle mesh --input-file sphere.cae --output-file sphere.cae --model-name sphere --part-name sphere --global-seed 0.15 --element-type C3D8
    - turbo-turtle image --input-file sphere.cae --output-file sphere.png --model-name sphere --part-name sphere
    - turbo-turtle export --input-file sphere.cae --model-name sphere --part-name sphere --element-type C3D8R
    - grep C3D8R sphere.inp
    - turbo-turtle sphere --inner-radius 1 --outer-radius 2 --output-file axisymmetric.cae --model-name axisymmetric --part-name axisymmetric --quadrant both --revolution-angle 0.0 --center 0.0 0.0
    - turbo-turtle partition --input-file axisymmetric.cae --output-file axisymmetric.cae --model-name axisymmetric --part-name axisymmetric --center 0.0 0.0 0 --xpoint 1.0 0.0 0.0 --zpoint 0.0 0.0 1.0 --plane-angle 45
    - turbo-turtle mesh --input-file axisymmetric.cae --output-file axisymmetric.cae --model-name axisymmetric --part-name axisymmetric --global-seed 0.15 --element-type CAX4
    - turbo-turtle image --input-file axisymmetric.cae --output-file axisymmetric.png --model-name axisymmetric --part-name axisymmetric
    - turbo-turtle export --input-file axisymmetric.cae --model-name axisymmetric --part-name axisymmetric --element-type CAX4R
    - grep CAX4R axisymmetric.inp
    - turbo-turtle sphere --inner-radius 1 --outer-radius 2 --output-file quarter-sphere.cae --model-name quarter-sphere --part-name quarter-sphere --quadrant both --revolution-angle 90.0 --center 0.0 0.0
    - turbo-turtle partition --input-file quarter-sphere.cae --output-file quarter-sphere.cae --model-name quarter-sphere --part-name quarter-sphere --center 0.0 0.0 0 --xpoint 1.0 0.0 0.0 --zpoint 0.0 0.0 1.0 --plane-angle 45
    - turbo-turtle mesh --input-file quarter-sphere.cae --output-file quarter-sphere.cae --model-name quarter-sphere --part-name quarter-sphere --global-seed 0.15 --element-type C3D8
    - turbo-turtle image --input-file quarter-sphere.cae --output-file quarter-sphere.png --model-name quarter-sphere --part-name quarter-sphere
    - turbo-turtle export --input-file quarter-sphere.cae --model-name quarter-sphere --part-name quarter-sphere --element-type C3D8R
    - grep C3D8R quarter-sphere.inp
    - turbo-turtle sphere --inner-radius 1 --outer-radius 2 --output-file offset-sphere.cae --model-name offset-sphere --part-name offset-sphere --quadrant both --revolution-angle 360.0 --center 1.0 1.0
    - turbo-turtle partition --input-file offset-sphere.cae --output-file offset-sphere.cae --model-name offset-sphere --part-name offset-sphere --center 1.0 1.0 0 --xpoint 2.0 1.0 0.0 --zpoint 1.0 1.0 1.0 --plane-angle 45
    - turbo-turtle mesh --input-file offset-sphere.cae --output-file offset-sphere.cae --model-name offset-sphere --part-name offset-sphere --global-seed 0.15 --element-type C3D8
    - turbo-turtle image --input-file offset-sphere.cae --output-file offset-sphere.png --model-name offset-sphere --part-name offset-sphere
    - turbo-turtle export --input-file offset-sphere.cae --model-name offset-sphere --part-name offset-sphere --element-type C3D8R
    - grep C3D8R offset-sphere.inp
    - turbo-turtle sphere --inner-radius 1 --outer-radius 2 --output-file eigth-sphere.cae --model-name eigth-sphere --part-name eigth-sphere --quadrant upper --revolution-angle 90.0 --center 0.0 0.0
    - turbo-turtle partition --input-file eigth-sphere.cae --output-file eigth-sphere.cae --model-name eigth-sphere --part-name eigth-sphere --center 0.0 0.0 0 --xpoint 1.0 0.0 0.0 --zpoint 0.0 0.0 1.0 --plane-angle 45
    - turbo-turtle mesh --input-file eigth-sphere.cae --output-file eigth-sphere.cae --model-name eigth-sphere --part-name eigth-sphere --global-seed 0.15 --element-type C3D8
    - turbo-turtle image --input-file eigth-sphere.cae --output-file eigth-sphere.png --model-name eigth-sphere --part-name eigth-sphere
    - turbo-turtle export --input-file eigth-sphere.cae --model-name eigth-sphere --part-name eigth-sphere --element-type C3D8R
    - grep C3D8R eigth-sphere.inp
    - turbo-turtle sphere --inner-radius 1 --outer-radius 2 --output-file half-sphere.cae --model-name half-sphere --part-name half-sphere --quadrant upper --revolution-angle 360.0 --center 0.0 0.0
    - turbo-turtle partition --input-file half-sphere.cae --output-file half-sphere.cae --model-name half-sphere --part-name half-sphere --center 0.0 0.0 0 --xpoint 1.0 0.0 0.0 --zpoint 0.0 0.0 1.0 --plane-angle 45
    - turbo-turtle mesh --input-file half-sphere.cae --output-file half-sphere.cae --model-name half-sphere --part-name half-sphere --global-seed 0.15 --element-type C3D8
    - turbo-turtle image --input-file half-sphere.cae --output-file half-sphere.png --model-name half-sphere --part-name half-sphere
    - turbo-turtle export --input-file half-sphere.cae --model-name half-sphere --part-name half-sphere --element-type C3D8R
    - grep C3D8R half-sphere.inp
    - turbo-turtle geometry --input-file turbo_turtle/tests/washer.csv --model-name washer --part-name washer --output-file washer.cae --revolution-angle 360.0
    - turbo-turtle geometry --input-file turbo_turtle/tests/vase.csv --model-name vase --part-name vase --output-file vase.cae --revolution-angle 360.0
    - turbo-turtle geometry --input-file turbo_turtle/tests/vase.csv --model-name vase-axisymmetric --part-name vase-axisymmetric --output-file vase-axisymmetric.cae --revolution-angle 0.0
    - turbo-turtle geometry --input-file turbo_turtle/tests/washer.csv turbo_turtle/tests/vase.csv --model-name multi-part-geometry --output-file multi-part-geometry.cae --revolution-angle 360.0
    - turbo-turtle cylinder --inner-radius 1 --outer-radius 2 --height 1 --model-name cylinder_3d --part-name cylinder_3d --output-file cylinder_3d.cae --revolution-angle 360.0
    - turbo-turtle cylinder --inner-radius 1 --outer-radius 2 --height 1 --model-name cylinder_2d --part-name cylinder_2d --output-file cylinder_2d.cae --revolution-angle 0.0
    # Separately handled _merge.py tests
    - turbo-turtle merge --input-file multi-part-geometry.cae sphere.cae --output-file merged-model.cae --merged-model-name merged-model --model-name multi-part-geometry sphere --part-name washer vase sphere
    - grep -iIre "SUCCESS" abaqus.rpy | grep "part 'washer'"
    - grep -iIre "SUCCESS" abaqus.rpy | grep "part 'vase'"
    - grep -iIre "SUCCESS" abaqus.rpy | grep "part 'sphere'"
    # Separately handled geometry
    - name='Turbo-Turtle-Tests'
    - abq2023 cae -noGui legacy_geometry.py
    - turbo-turtle partition --input-file ${name}.cae --output-file ${name}.cae --model-name ${name} --part-name seveneigths-sphere --center 0 0 0 --xpoint 1 0 0 --zpoint 0 0 1 --plane-angle 45
    - turbo-turtle image --input-file ${name}.cae --model-name ${name} --output-file seveneigths-sphere.png --part-name seveneigths-sphere
    - turbo-turtle partition --input-file ${name}.cae --output-file ${name}.cae --model-name ${name} --part-name swiss-cheese --center 0 0 0 --xpoint 1 0 0 --zpoint 0 0 1 --plane-angle 45
    - turbo-turtle image --input-file ${name}.cae --model-name ${name} --output-file swiss-cheese.png --part-name swiss-cheese
