package:
  name: turbo_turtle
  # TODO: Figure out how to use pyproject.toml and a Conda build Jinja template
  version: {{ VERSION }}

about:
  home: https://re-git.lanl.gov/aea/python-projects/turbo_turtle
  summary: 'Partition hollow, spherical bodies using a turtle shell'
  description: |
    Partition hollow, spherical bodies using a turtle shell
  doc_url: https://aea.re-pages.lanl.gov/python-projects/turbo_turtle/main/index.html
  dev_url: https://re-git.lanl.gov/aea/python-projects/turbo_turtle

source:
  path: '..'

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ VERSION }}
  script:
    # Build and install Conda package
    - $PYTHON -m build --no-isolation
    - $PYTHON -m pip install dist/$PKG_NAME-$PKG_VERSION.tar.gz --no-deps --ignore-installed -v --no-build-isolation
    - $PYTHON -m pip show $PKG_NAME
    # Build man page and HTML documentation to bundle in Conda package
    - scons man html
    - $PYTHON package_documentation.py
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - scons >=4
    - setuptools_scm[toml] >=6.2,<8
    - sphinx >=5.1
    - sphinx-argparse
    - sphinx-copybutton >=0.5.1
    - sphinx_rtd_theme >=1
    - waves >=0.7.2
  host:
    - python
    - python-build
    - pip
    - setuptools >=62
    - setuptools_scm[toml] >=6.2,<8
  run:
    - python >=3.8

test:
  requires:
  imports:
    - turbo_turtle
  source_files:
    - test_geometry.py
  commands:
    - test_root=${PWD}
    - name='Turbo-Turtle-Tests'
    - turbo-turtle -h
    - turbo-turtle docs -h
    - turbo-turtle docs --print-local-path
    - turbo-turtle sphere -h
    - turbo-turtle partition -h
    - turbo-turtle image -h
    - turbo-turtle sphere --inner-radius 1 --outer-radius 2 --output-file sphere.cae --model-name sphere --part-name sphere --quadrant both --angle 360.0 --center 0.0 0.0
    - turbo-turtle partition --input-file sphere.cae --output-file sphere.cae --model-name sphere --part-name sphere --center 0.0 0.0 0 --xpoint 1.0 0.0 0.0 --zpoint 0.0 0.0 1.0 --plane-angle 45
    - turbo-turtle sphere --inner-radius 1 --outer-radius 2 --output-file axisymmetric.cae --model-name axisymmetric --part-name axisymmetric --quadrant both --angle 0.0 --center 0.0 0.0
    - turbo-turtle partition --input-file axisymmetric.cae --output-file axisymmetric.cae --model-name axisymmetric --part-name axisymmetric --center 0.0 0.0 0 --xpoint 1.0 0.0 0.0 --zpoint 0.0 0.0 1.0 --plane-angle 45
    - turbo-turtle sphere --inner-radius 1 --outer-radius 2 --output-file quarter-sphere.cae --model-name quarter-sphere --part-name quarter-sphere --quadrant both --angle 90.0 --center 0.0 0.0
    - turbo-turtle partition --input-file quarter-sphere.cae --output-file quarter-sphere.cae --model-name quarter-sphere --part-name quarter-sphere --center 0.0 0.0 0 --xpoint 1.0 0.0 0.0 --zpoint 0.0 0.0 1.0 --plane-angle 45
    - turbo-turtle sphere --inner-radius 1 --outer-radius 2 --output-file offset-sphere.cae --model-name offset-sphere --part-name offset-sphere --quadrant both --angle 360.0 --center 1.0 1.0
    - turbo-turtle partition --input-file offset-sphere.cae --output-file offset-sphere.cae --model-name offset-sphere --part-name offset-sphere --center 1.0 1.0 0 --xpoint 2.0 1.0 0.0 --zpoint 1.0 1.0 1.0 --plane-angle 45
    - turbo-turtle sphere --inner-radius 1 --outer-radius 2 --output-file eigth-sphere.cae --model-name eigth-sphere --part-name eigth-sphere --quadrant upper --angle 90.0 --center 0.0 0.0
    - turbo-turtle partition --input-file eigth-sphere.cae --output-file eigth-sphere.cae --model-name eigth-sphere --part-name eigth-sphere --center 0.0 0.0 0 --xpoint 1.0 0.0 0.0 --zpoint 0.0 0.0 1.0 --plane-angle 45
    - turbo-turtle sphere --inner-radius 1 --outer-radius 2 --output-file half-sphere.cae --model-name half-sphere --part-name half-sphere --quadrant upper --angle 360.0 --center 0.0 0.0
    - turbo-turtle partition --input-file half-sphere.cae --output-file half-sphere.cae --model-name half-sphere --part-name half-sphere --center 0.0 0.0 0 --xpoint 1.0 0.0 0.0 --zpoint 0.0 0.0 1.0 --plane-angle 45
    - abq2023 cae -noGui test_geometry.py
    - turbo-turtle partition --input-file ${name}.cae --output-file ${name}.cae --model-name ${name} --part-name seveneigths-sphere --center 0 0 0 --xpoint 1 0 0 --zpoint 0 0 1 --plane-angle 45
    - turbo-turtle partition --input-file ${name}.cae --output-file ${name}.cae --model-name ${name} --part-name swiss-cheese --center 0 0 0 --xpoint 1 0 0 --zpoint 0 0 1 --plane-angle 45
