# Reference: https://github.com/softprops/action-gh-release
name: Release on new tags

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: 'true'
          fetch-depth: 0
      - name: Install latexmk
        run: sudo apt-get update && sudo apt-get install -y texlive texlive-latex-extra latexmk
      - name: MiniConda setup
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: ""
      - name: Conda environment
        shell: bash -el {0}
        run: conda install boa conda-build 'scons>=4' 'waves>=0.13' 'lazy_loader>=0.4' 'setuptools>=64' 'setuptools_scm>=8' 'sphinx>=5.1' sphinx-argparse 'sphinx-copybutton>=0.5.1' 'sphinx-book-theme' sphinxcontrib-bibtex pytest --yes --channel conda-forge
      - name: Build documentation
        shell: bash -el {0}
        run: scons latexpdf
      - name: Conda build
        shell: bash -el {0}
        run: VERSION=$(python -m setuptools_scm) conda mambabuild recipe --channel conda-forge --no-anaconda-upload --output-folder conda-bld
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/docs/latex/turbo-turtle-${{ github.ref_name }}.pdf
            conda-bld/noarch/turbo-turtle-${{ github.ref_name }}-py_0.tar.bz2
          body: "Changelog: https://lanl-aea.github.io/turbo-turtle/changelog.html. Installation: https://lanl-aea.github.io/turbo-turtle/installation.html"
